# Generated by Django 4.1.7 on 2023-04-03 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('max_score', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Количество баллов за вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='User_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_exam.role', verbose_name='Роль')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Тест')),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_exam.role', verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='SelectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False, verbose_name='Правильный ответ?')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='project_exam.question', verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_points', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Полученный балл')),
                ('test_date', models.DateTimeField(auto_now=True, verbose_name='Дата прохождения теста')),
                ('result', models.BooleanField(default=False)),
                ('tests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_exam.tests', verbose_name='Тест')),
                ('user_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Экзаменуемый')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_exam.tests', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='Available_tests_for_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unavailable_tests', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_exam.tests', verbose_name='Не доступный тест')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_exam.user_role')),
            ],
        ),
        migrations.CreateModel(
            name='AnswersOnQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False, verbose_name='Правильный ответ?')),
                ('number_of_points', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Полученный балл')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_exam.selectanswer')),
                ('examUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_exam.question')),
                ('tests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_exam.tests')),
            ],
        ),
    ]
