# Generated by Django 4.1.7 on 2023-04-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_exam', '0002_close_tests_for_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='done_score',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6, null=True, verbose_name='Пороговый балл'),
        ),
        migrations.AddField(
            model_name='tests',
            name='number_of_questions',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6, null=True, verbose_name='Количество вопросов'),
        ),
        migrations.AddField(
            model_name='tests',
            name='time',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6, null=True, verbose_name='Время'),
        ),
    ]
