# Generated by Django 4.2.10 on 2024-02-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_exam', '0009_users_reg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_tests_for_users',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Test date'),
        ),
    ]
